FROM node:22-alpine3.20

RUN apk add --no-cache chromium ca-certificates ttf-freefont font-noto-emoji

ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV CHROMIUM_PATH=/usr/bin/chromium-browser

RUN npx puppeteer browsers install chrome

RUN mkdir -p /svr/app
WORKDIR /svr/app
RUN npm i -g @nestjs/cli

COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .

EXPOSE $BACKEND_PORT
CMD ["npm", "run", "start:debug"]
