FROM node:22-alpine3.20

RUN mkdir -p /svr/app
WORKDIR /svr/app
RUN npm i -g @nestjs/cli

COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .

EXPOSE $BACKEND_PORT
CMD ["npm", "run", "start:debug"]